const express = require('express')
const applyMiddleware = require('./middleware.js')
const graphqlHTTP = require('express-graphql')
const schema = require('../schema/schema.js')
const expressPlayground = require('graphql-playground-middleware-express')